#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================
name: udpxy

on:
  workflow_dispatch:

jobs:
  make-run:
    runs-on: ubuntu-22.04

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@main

      - name: 📦 安装 makeself 工具
        run: sudo apt-get update && sudo apt-get install -y makeself curl

      - name: 🚀 下载 udpxy的所有ipk
        run: |
          chmod +x shell/udpxy.sh
          ./shell/udpxy.sh

      - name: 📋 拷贝 install.sh 到各平台目录
        run: |
          chmod +x shell/install.sh
          cp shell/install.sh x86_64/install.sh
          cp shell/install.sh aarch64_generic/install.sh
          cp shell/install.sh aarch64_cortex-a76/install.sh

      - name: 🔍 提取版本号并打包
        id: pack
        run: |
          mkdir -p output

          # 获取版本
          APP_IPK=$(ls aarch64_generic/luci-app-udpxy_*.ipk | head -n 1)
          VERSION=$(basename "$APP_IPK" | sed -n 's/^luci-app-udpxy_\(.*\)_all\.ipk$/\1/p')

          if [ -z "$VERSION" ]; then
            echo "❌ 无法提取版本号"
            exit 1
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "打印版本号"
          echo $VERSION

          # 打包各个平台
          for PLATFORM in x86_64 aarch64_generic aarch64_cortex-a76; do
            makeself "$PLATFORM" "output/luci-app-udpxy-${VERSION}_${PLATFORM}.run" \
              "udpxy ${PLATFORM} Installer v${VERSION}" ./install.sh
          done

      - name: Set version name without special chars
        id: clean_version
        run: |
            version="${{ steps.pack.outputs.version }}"
            version=${version%%~*}
            echo "VERSION_CLEAN=$version" >> $GITHUB_ENV
            echo "cleaned_version=$version" >> $GITHUB_OUTPUT

      - name: 整理文件
        run: |
          mkdir -p dcx
          mv output/*.run dcx/
          
      - name: 上传软件
        uses: actions/upload-artifact@main
        with:
          name: "udpxy-${{ steps.clean_version.outputs.cleaned_version }}"
          path: ${{ github.workspace }}/dcx          
